### ISSUE TITLE
pom.xml file outputting built jar to its own jar folder

### ISSUE THREAD

**Issue by Cole-99** [4rg0n/songs-of-syx-mod-example#5]
I noticed the pom.xml file has the following config for outputting a mod's script jar file
`<mod.script.output.directory>${mod.files.build.output.directory}/script/jar</mod.script.output.directory>`

This makes it so the mod's script does not load in correctly, so it does not show in the script selection before creating a world. Should it instead be what I have below?

`<mod.script.output.directory>${mod.files.build.output.directory}/script</mod.script.output.directory>`

Edit -- Forgot to mention this is V66, I'm not aware if this is different in V65.

**Comment by 4rg0n** [comment]
Yes, it's not updated for v66 yet. The path changed.
I've updated it =)
